name = "Hugo Open Props"
license = "MIT"
licenselink = "https://github.com/ricardoom/nbubTheme/blob/main/LICENSE"
description = "A starter theme using Open Props, [CUBE] & sundry other approaches"
homepage = "https://example.com"
tags = ["Open Props", "C.U.B.E."]
features = ["rational scaling"]
min_version = "0.97.0"

[author]
  name = "Ricardo E. Galvez"
  homepage = "https://ricardogalvez.design"
